### ISSUE TITLE
Timecodes don't match, seems to play past end of file

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [podigee/podigee-podcast-player#27]
I'm using the Podigee player on my [site](https://swiss-sided-dice.ch), and it looks good, but when playing the first episode, the timestamps from the chaptermarks don't match the content they did when I played the file in VLC and in Audacity.

On top of that, when it reaches the end of the file it reaches the final timecode (03:26:34) before the file is actually at the end and stops counting seconds (because it's at 03:26:34/-00:00:00) _but still plays the end of the file!_

The file is Joint Stereo mp3, VBR level 6 (ended up at 89kbit/s) at 44.1khz.

**Comment by MyrionPhoenixmoon** [comment]
So here's what I found by comparing to VLC and stopping time:

The chaptermarks are off by roughly -10s i.e. the chapter mark for 13:55 plays the content for 13:45.

The end is ~30s after the player says it is.

**Comment by MyrionPhoenixmoon** [comment]
The issue was that the file was VBR - apparently this causes issues when seeking. I was pointed to this problem and the solution by an auphonic dev on Sendegate.

Feel free to close this issue, although I do think that you should properly support VBR files at some point.

**Comment by benzimmer** [comment]
The problem here is that we have to rely on the browser to report the correct time, which it doesn't for VBR files.

Some external resources on this:

- https://marco.org/2016/08/15/vbr-mp3-plea (iOS related)
- https://bugs.chromium.org/p/chromium/issues/detail?id=689334&q=vbr&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
- https://bugzilla.mozilla.org/show_bug.cgi?id=1070485

Seems like Firefox fixed this recently. I'll leave this open for now so we can do some research when there is some time. In the meantime: Don't use VBR 🙁
